version: '3.8'

services:
  backend:
    build: ./backend
    container_name: habit_tracker_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # env_file:
    #   - ./backend/.env.dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: habit_tracker_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: habit_tracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=habit_tracker_db

volumes:
  postgres_data:
